name: publish

on: 
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Use Node.js
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm test              
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest    
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/index.pdf
          asset_name: abap-code-review-guide.pdf
          tag: latest
          overwrite: true
